teiid:
  image: jboss/teiid
#  ports:
  # - "9990:9990"
  # - "31000:31000"
  links:
    - base_mysql
    - mysql_vertical_mysql2
  volumes_from:
    - data
  volumes:
   -  ./../../../teiid/standalone/configuration:/opt/jboss/wildfly/standalone/configuration
   - ./../../../teiid/standalone/deployment:/opt/jboss/wildfly/standalone/deployments
   - ./../../../teiid/modules:/opt/jboss/wildfly/modules
ontop:
  build: ../../../single-server/ontop/ontop
  links:
     - teiid
  ports:
     - "3008:8080"
  volumes:
   - ./../../../single-server/ontop/ontop-mapping:/ontop
