FROM java



RUN wget https://sourceforge.net/projects/ontop4obda/files/ontop-1.18.0/ontop-jetty-bundle-1.18.0.1.zip && unzip ontop-jetty-bundle-1.18.0.1.zip && cd ontop-jetty-bundle-1.18.0.1 && export JETTY_HOME = /ntop-jetty-bundle-1.18.0.1/
